version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${POSTGRES_USER:-user}" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-database}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/data/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  logstash:
    container_name: logstash
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-database}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - SCHEDULE=${SCHEDULE:-}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local